### ISSUE TITLE
How to test directories?

### ISSUE THREAD

**Issue by liyishuai** [ejgallego/coq-plugin-template#9]
Say, QuickChick tests its plugin with a bunch of examples: https://github.com/QuickChick/QuickChick/blob/235f6f2156b06239d10e971b7f229f18b73fb67c/Makefile#L66-L78 , which includes building entire directories like https://github.com/QuickChick/QuickChick/tree/master/tutorials .

How should we write the Dune rules?

**Comment by palmskog** [comment]
@liyishuai this is a question best asked in the [Dune devs & users stream](https://coq.zulipchat.com/#narrow/stream/240550-Dune-devs-.26-users) in the Coq Zulip. All I can do here is point you to some examples of Dune-driven test directories:
- https://github.com/ejgallego/coq-serapi/tree/main/tests/genarg
- https://github.com/coq-community/stalmarck/tree/master/tests

The only testing that is likely to be demonstrated here is for running a plugin inside Coq.

**Comment by ejgallego** [comment]
There are ways the question can be understood:
- how to setup the rules for testing: in this case, there are several approaches, usually you either use Dune built-in testing support (like CRAM or others) or generate your own rules (as in SerAPI), this is often boring.
- once you have rules (and aliases), you can just use `dune build dir/sub_dir/@alias` to build the targets in a subdir.
